export const GET_WEATHER_DATA_START = "GET_WEATHER_DATA_START";
export const GET_WEATHER_DATA_SUCCESS = "GET_WEATHER_DATA_SUCCESS";
export const GET_WEATHER_DATA_FAILURE = "GET_WEATHER_DATA_FAILURE";
